
services:
- type: web
  name: django-api
  runtime: python
  repo: https://github.com/wusixuan0/django-api
  plan: free
  envVars:
  - key: DOPPLER_PROJECT
    sync: false
  - key: DOPPLER_ENVIRONMENT
    sync: false
  - key: DOPPLER_CONFIG
    sync: false
  - key: DATABASE_URL
    sync: false
  region: ohio
  buildCommand: "./build.sh"
  startCommand: python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker
version: "1"
