# Generated by Django 5.0.7 on 2024-08-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(default='Canada', max_length=100),
            preserve_default=False,
        ),
    ]
