# Generated by Django 5.0.7 on 2024-08-03 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_person_country'),
        ('api', '0003_person_discipline'),
    ]

    operations = [
    ]
